### ISSUE TITLE
Milestone 01 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/caretcompaR#14]
Hello,

Great job on your milestone 01 submission. I just have some comments below,
- I like that you used `roxygen2` in generating function documentation.
- You can default values for parameters of different functions rather than throwing an error if one parameter is missing, such as `comparison_viz(comparison, choice = accuracy)`.
- In the `test_train_test_acc_time.R`, in the "Output should be 1 dataframe" test, you used `length()` expecting the output to be "1", but that will not be the case as it counts the number of columns.
- You should test that `y_traing` and `y_test` are one dimensional vectors.

Thanks!

**Comment by talhaadnan100** [comment]
Appreciate the constructive feedback. The suggestions have been incorporated in the latest revisions to the package.
