### ISSUE TITLE
Feedback of Milestone 3

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/caretcompaR#39]
very good job, guys! You don't have big problems this time, just one advise below:
- Please add the screenshot when you passed all test case in case my library of program backend does not work appropriately.

**Comment by Doooooris** [comment]
-Please build vigenettes next time using devtools::build_vignettes(). You can found more useful information online.

**Comment by Birinder1469** [comment]
Thanks for the encouragement Doris,
- Added the Snapshots in Milestone 3. The Continuous integration is showing the coverage results in Final Milestone.
- Updated the Vignette and added the details of how to use it in the Read me.
